source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'rails', '~> 5.2.1'
# Storage
gem 'pg', '>= 0.18', '< 2.0'
# Deployment
gem 'puma', '~> 4.3'
# Auth
gem 'devise'
# Others
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Debugging
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Unit Tests
  gem 'rspec-rails', '~> 3.5'
end

group :development do
  # Auto-update
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'factory_bot_rails', '~> 4.0'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'faker', '~> 1.9'
  gem 'database_cleaner', '~> 1.7'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
