#!/bin/sh

set -x
rm -f tmp/pids/server.pid

postgres_ready() {
ruby << END

require 'pg'
begin
	conn = PG::Connection.open(:host => ENV["POSTGRES_HOST"],
								:dbname => ENV["POSTGRES_DB"],
								:user => ENV["POSTGRES_USER"])
rescue PG::Error => e
	exit 1
ensure
	conn.close if conn
end
exit 0

END
}

until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'


RAILS_ENV=development bundle exec rake db:migrate
RAILS_ENV=development bundle exec rails s -p 8003 -b '0.0.0.0'
